/** Базовые компоненты дизайн-системы (F2, F5). Единая точка импорта для экранов. */

export { default as SyButton } from './SyButton.vue'
export { default as SyCopyButton } from './SyCopyButton.vue'
export { default as SyEmptyState } from './SyEmptyState.vue'
export { default as SyField } from './SyField.vue'
export { default as SyInput } from './SyInput.vue'
export { default as SyListItem } from './SyListItem.vue'
export { default as SyModal } from './SyModal.vue'
export { default as SySecretField } from './SySecretField.vue'
export { default as SySelect } from './SySelect.vue'
export type { SySelectOption } from './SySelect.vue'
export { default as SyToast } from './SyToast.vue'
export { default as SyToggle } from './SyToggle.vue'
export { iconHue, iconInitials } from './localIcon'
export { VAULT_COLOR_NAMES, vaultColorVar } from './vaultColor'
